// Code generated by capnpc-go. DO NOT EDIT.

package main

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
)

type Way capnp.Struct

// Way_TypeID is the unique identifier for the type Way.
const Way_TypeID = 0xa4b9c59286b69600

func NewWay(s *capnp.Segment) (Way, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 72, PointerCount: 5})
	return Way(st), err
}

func NewRootWay(s *capnp.Segment) (Way, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 72, PointerCount: 5})
	return Way(st), err
}

func ReadRootWay(msg *capnp.Message) (Way, error) {
	root, err := msg.Root()
	return Way(root.Struct()), err
}

func (s Way) String() string {
	str, _ := text.Marshal(0xa4b9c59286b69600, capnp.Struct(s))
	return str
}

func (s Way) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Way) DecodeFromPtr(p capnp.Ptr) Way {
	return Way(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Way) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Way) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Way) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Way) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Way) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Way) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Way) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Way) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Way) Ref() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Way) HasRef() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Way) RefBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Way) SetRef(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Way) MaxSpeed() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Way) SetMaxSpeed(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Way) MinLat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Way) SetMinLat(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s Way) MinLon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(16))
}

func (s Way) SetMinLon(v float64) {
	capnp.Struct(s).SetUint64(16, math.Float64bits(v))
}

func (s Way) MaxLat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(24))
}

func (s Way) SetMaxLat(v float64) {
	capnp.Struct(s).SetUint64(24, math.Float64bits(v))
}

func (s Way) MaxLon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(32))
}

func (s Way) SetMaxLon(v float64) {
	capnp.Struct(s).SetUint64(32, math.Float64bits(v))
}

func (s Way) Nodes() (Coordinates_List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return Coordinates_List(p.List()), err
}

func (s Way) HasNodes() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Way) SetNodes(v Coordinates_List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewNodes sets the nodes field to a newly
// allocated Coordinates_List, preferring placement in s's segment.
func (s Way) NewNodes(n int32) (Coordinates_List, error) {
	l, err := NewCoordinates_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Coordinates_List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s Way) Lanes() uint8 {
	return capnp.Struct(s).Uint8(40)
}

func (s Way) SetLanes(v uint8) {
	capnp.Struct(s).SetUint8(40, v)
}

func (s Way) AdvisorySpeed() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(48))
}

func (s Way) SetAdvisorySpeed(v float64) {
	capnp.Struct(s).SetUint64(48, math.Float64bits(v))
}

func (s Way) Hazard() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Way) HasHazard() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Way) HazardBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Way) SetHazard(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Way) OneWay() bool {
	return capnp.Struct(s).Bit(328)
}

func (s Way) SetOneWay(v bool) {
	capnp.Struct(s).SetBit(328, v)
}

func (s Way) MaxSpeedForward() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(56))
}

func (s Way) SetMaxSpeedForward(v float64) {
	capnp.Struct(s).SetUint64(56, math.Float64bits(v))
}

func (s Way) MaxSpeedBackward() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(64))
}

func (s Way) SetMaxSpeedBackward(v float64) {
	capnp.Struct(s).SetUint64(64, math.Float64bits(v))
}

func (s Way) WindingForwardLevel() uint8 {
	return capnp.Struct(s).Uint8(42)
}

func (s Way) SetWindingForwardLevel(v uint8) {
	capnp.Struct(s).SetUint8(42, v)
}

func (s Way) WindingBackwardLevel() uint8 {
	return capnp.Struct(s).Uint8(43)
}

func (s Way) SetWindingBackwardLevel(v uint8) {
	capnp.Struct(s).SetUint8(43, v)
}

func (s Way) WindingForwardScore() uint8 {
	return capnp.Struct(s).Uint8(44)
}

func (s Way) SetWindingForwardScore(v uint8) {
	capnp.Struct(s).SetUint8(44, v)
}

func (s Way) WindingBackwardScore() uint8 {
	return capnp.Struct(s).Uint8(45)
}

func (s Way) SetWindingBackwardScore(v uint8) {
	capnp.Struct(s).SetUint8(45, v)
}

func (s Way) WindingForwardConfidence() uint8 {
	return capnp.Struct(s).Uint8(46)
}

func (s Way) SetWindingForwardConfidence(v uint8) {
	capnp.Struct(s).SetUint8(46, v)
}

func (s Way) WindingBackwardConfidence() uint8 {
	return capnp.Struct(s).Uint8(47)
}

func (s Way) SetWindingBackwardConfidence(v uint8) {
	capnp.Struct(s).SetUint8(47, v)
}

func (s Way) SafeSpeeds() (capnp.Float64List, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return capnp.Float64List(p.List()), err
}

func (s Way) HasSafeSpeeds() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Way) SetSafeSpeeds(v capnp.Float64List) error {
	return capnp.Struct(s).SetPtr(4, v.ToPtr())
}

// NewSafeSpeeds sets the safeSpeeds field to a newly
// allocated capnp.Float64List, preferring placement in s's segment.
func (s Way) NewSafeSpeeds(n int32) (capnp.Float64List, error) {
	l, err := capnp.NewFloat64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Float64List{}, err
	}
	err = capnp.Struct(s).SetPtr(4, l.ToPtr())
	return l, err
}

// Way_List is a list of Way.
type Way_List = capnp.StructList[Way]

// NewWay creates a new list of Way.
func NewWay_List(s *capnp.Segment, sz int32) (Way_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 72, PointerCount: 5}, sz)
	return capnp.StructList[Way](l), err
}

// Way_Future is a wrapper for a Way promised by a client call.
type Way_Future struct{ *capnp.Future }

func (f Way_Future) Struct() (Way, error) {
	p, err := f.Future.Ptr()
	return Way(p.Struct()), err
}

type Coordinates capnp.Struct

// Coordinates_TypeID is the unique identifier for the type Coordinates.
const Coordinates_TypeID = 0x922b57c60c6a46d1

func NewCoordinates(s *capnp.Segment) (Coordinates, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Coordinates(st), err
}

func NewRootCoordinates(s *capnp.Segment) (Coordinates, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Coordinates(st), err
}

func ReadRootCoordinates(msg *capnp.Message) (Coordinates, error) {
	root, err := msg.Root()
	return Coordinates(root.Struct()), err
}

func (s Coordinates) String() string {
	str, _ := text.Marshal(0x922b57c60c6a46d1, capnp.Struct(s))
	return str
}

func (s Coordinates) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Coordinates) DecodeFromPtr(p capnp.Ptr) Coordinates {
	return Coordinates(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Coordinates) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Coordinates) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Coordinates) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Coordinates) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Coordinates) Latitude() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Coordinates) SetLatitude(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Coordinates) Longitude() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Coordinates) SetLongitude(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

// Coordinates_List is a list of Coordinates.
type Coordinates_List = capnp.StructList[Coordinates]

// NewCoordinates creates a new list of Coordinates.
func NewCoordinates_List(s *capnp.Segment, sz int32) (Coordinates_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[Coordinates](l), err
}

// Coordinates_Future is a wrapper for a Coordinates promised by a client call.
type Coordinates_Future struct{ *capnp.Future }

func (f Coordinates_Future) Struct() (Coordinates, error) {
	p, err := f.Future.Ptr()
	return Coordinates(p.Struct()), err
}

type Offline capnp.Struct

// Offline_TypeID is the unique identifier for the type Offline.
const Offline_TypeID = 0xcb5ff253617678e0

func NewOffline(s *capnp.Segment) (Offline, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 2})
	return Offline(st), err
}

func NewRootOffline(s *capnp.Segment) (Offline, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 2})
	return Offline(st), err
}

func ReadRootOffline(msg *capnp.Message) (Offline, error) {
	root, err := msg.Root()
	return Offline(root.Struct()), err
}

func (s Offline) String() string {
	str, _ := text.Marshal(0xcb5ff253617678e0, capnp.Struct(s))
	return str
}

func (s Offline) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Offline) DecodeFromPtr(p capnp.Ptr) Offline {
	return Offline(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Offline) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Offline) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Offline) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Offline) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Offline) MinLat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Offline) SetMinLat(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Offline) MinLon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Offline) SetMinLon(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s Offline) MaxLat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(16))
}

func (s Offline) SetMaxLat(v float64) {
	capnp.Struct(s).SetUint64(16, math.Float64bits(v))
}

func (s Offline) MaxLon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(24))
}

func (s Offline) SetMaxLon(v float64) {
	capnp.Struct(s).SetUint64(24, math.Float64bits(v))
}

func (s Offline) Ways() (Way_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Way_List(p.List()), err
}

func (s Offline) HasWays() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Offline) SetWays(v Way_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewWays sets the ways field to a newly
// allocated Way_List, preferring placement in s's segment.
func (s Offline) NewWays(n int32) (Way_List, error) {
	l, err := NewWay_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Way_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s Offline) Overlap() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(32))
}

func (s Offline) SetOverlap(v float64) {
	capnp.Struct(s).SetUint64(32, math.Float64bits(v))
}

func (s Offline) SchemaVersion() uint16 {
	return capnp.Struct(s).Uint16(40)
}

func (s Offline) SetSchemaVersion(v uint16) {
	capnp.Struct(s).SetUint16(40, v)
}

func (s Offline) SigmoidHash() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Offline) HasSigmoidHash() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Offline) SigmoidHashBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Offline) SetSigmoidHash(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// Offline_List is a list of Offline.
type Offline_List = capnp.StructList[Offline]

// NewOffline creates a new list of Offline.
func NewOffline_List(s *capnp.Segment, sz int32) (Offline_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 48, PointerCount: 2}, sz)
	return capnp.StructList[Offline](l), err
}

// Offline_Future is a wrapper for a Offline promised by a client call.
type Offline_Future struct{ *capnp.Future }

func (f Offline_Future) Struct() (Offline, error) {
	p, err := f.Future.Ptr()
	return Offline(p.Struct()), err
}

const schema_da3a0d9284ca402f = "x\xda\xa4\xd4Mh\x1ce\x18\x07\xf0\xff\xff\x9d\xc9n" +
	"\xd2lv\xb3}\xdf\xa3\x12\x11\x846\xb5\x1fQ\x0f\x12" +
	"*\xadi\x0d\xa1D\xcct\xa2\x89\xa2\xe8\xeb\xeel2" +
	"\xba\x99\x89\xb3\xdbd#\x8a\x1fDQ\xa1Ps\x10\x84" +
	"\x82 \x0a\xc5\x9bR\x04\x0fB/*\xd6\x0aM\xb1\xd0" +
	"J\x84\x08\x1e\x14<\x88 T\x10W\x9e\xd9\xecnJ" +
	"\xeb\xa9\xb7\x9d\xdf\xf3\xbc\x1f\x93<\xff90\xab\x0e\xbb" +
	"#\x03\xb1\x82\xf2n\xeb\xc94\xd7\xc7\x9f\xcb}=\xb3" +
	"g\x0d^\x9e\xaa\xb9\xff\xf0\xf9\xd5\xb5\x81\xd1\x1f\xe1f" +
	"\x01};/\xe9\xdd\x94_wq\x19\xfc\xf7\xbd\xcf\xdf" +
	"\\\xfb\xea\x8b\x8f\xbc<\xfb\xba\x9d==\xd2\xf06\xd7" +
	"\xf4\xbb\xd2z\xefI~\xe0\x82\xcd\xcd\xc6\x92\xf5\xff|" +
	"\xfa;\xd97\xb3\xad[I\xf7\xf7\x99\xcf\xf4\xe5\x8ct" +
	"\xafg\xbe!\xf66\xe3J\xa5\x1aF\xc1>U\xb2\x8b" +
	"\xd1\xe2\xe8\x918N\xcaad\xeb\x01kS\xa4\xd7\xeb" +
	"\xb8\x80K\xa0\xb8\xfb\x18\xe0\xedr\xe8\xdd\xa7X$\x0d" +
	"\x05G\x8e\x03\xde\x01\x87\xdeA\xc5f\xd5\xd6\xc3\xfa\x89" +
	"r\x00\x80\xfdP\xec\x07\x9b\xd58\x9a\x13\x04\x83\x8e\xb5" +
	"\x8fd\xeb\xc8\x19\xcb\x159j\xba}\x94~@\x0d\x03" +
	"\xfe\xfd\xca\xa1\x7fTuO\xd3\x0f\xaa;\x01\xff\xa0\xf8" +
	"\x84R\xa42T\x80~H\x1d\x03\xfc\xa3\xc2S\xd2\xee" +
	"\xd0\xd0\x01\xf4\xc3j\x14\xf0'\xc4\xa7\xc5]e\xe8\x02" +
	"\xdaK}R|V\xbc\xc71\xec\x01\xf4\xa3\xa9O\x89" +
	"?)\x9eq\x0d3\x80~<\xf5i\xf1g\xc4\xb3\xca" +
	"\xa4\xff\x9a\xa7\xd4=\x80?+^\x17\xef\xdde\xd8\x0b" +
	"\xe8\x17R\xaf\x8a7\xc4\xfb2\x86}\x80>\xa1\x12\xc0" +
	"\xaf\x8b\xbf*\xbe\xc31\xdc\x01\xe8\x97\xd3\xfd\x1b\xe2\xab" +
	"Jq\xa4\x7f\x82\x86\xfd\x80~--\xbc$\x85\xb7d" +
	"A.k\x98\x03\xf4\x1b\xeau\xc0_\x15?%>\xd0" +
	"k8\x00\xe8\x93\xea\x1d\xc0?%~Z<?l\x98" +
	"\x07\xf4\xfb\xeaC\xc0?-~F\xbc\xb0\xc7\xb0\x00\xe8" +
	"\x8f\xd5'\x80\x7fF\xfc\xac\xf8\xe0\xdd\x86\x83\x80\xfe4" +
	"\xed?+~N\xbc\xb8\xd7\xb0\x08\xe8/\xd3\xfes\xe2" +
	"\x17\xc4w\xee3\xdc\x09\xe8o\xd5y\xc0\xbf(\xbe!" +
	"\xae\xf7\x1bj@_U\x97\x00\x7fS\xfcwq\xe3\x1a" +
	"\x1a@\xff\xa6\x9e\x00\xfc_\xc5]G\xb1\x10\xd9\x85\x80" +
	"9(\xe6\xc0l\x12T\xda\xbf\x9b\x0b\xb6\xe1/\x06A" +
	"y\xdbD\x1dZ\x08\xa3I[\xbf\xee1\x8e\xba\x8f\xb6" +
	"q]\xd56\xb6U\x87\xa2\xb8\x1c\xd4\x98\x07\xa7\x1cr" +
	"\xb0\x9b@Pp\xa8j\xa3\xa0\xc6\x0c\x143`\xd3\x96" +
	"\x97\xc2Z\x9c\xac`(\xbdCg\xcfy\xfb\xa2M\xca" +
	"\xed;\x1e\x8a\xa3`\xc6\xae\x90P\xe4\xb6+s<N" +
	"\x96mR\xeeF\xa1S\x19\xb3\xa5\xe7\xd3R\xb7\xb6\x1c" +
	"F\xe50\x9a\x1bgk\xd1d\x90]\x0a\xaa\x9d\x9bl" +
	"U\xc7\xb8\xb5p\xb2\x10\xdc\xa4\xdc^\xec\x97\xb2q\x12" +
	"\xfc\xefb\xbfP\xbaIy\\\xb5\x16\x1f\x89\xa3JX" +
	"\x0e\xa2R\x00\xdc\xb0\x85\xda\xda\xa2\xd3\xc4\xee>5[" +
	"\x09\xe4\xf5\xe0\x94;\x7fay\xbb\xfc\x8d\x81\x7f\xa42" +
	"\x94>K\xe8\xef\xe8|_\xd6G\x01\xef\x82C\xef\xca" +
	"\xb6\xef\xcbe\xc1\x8b\x0e\xbd\x0d\xc5\xa2j\xe5\xbdxU" +
	"\xf0\x07\x87\xde\xa6\x84\xddI\xc3^\xfcI\xf0\x8aC\xef" +
	"\x17E\xbai\xd0\x8b?\x0f\x03\xde\x86C\xef\x9a\xa4\xdc" +
	"MS^\xfck\x0c\xf0\xfep\xe8\xfd#\x117i\xc4" +
	"\x8b\x7f'\x80wM\xe6\x91\x12p\xb6\x02N>\x0b\x1c" +
	"\xa7C?GuK\x93WX\xb6+\xdd\xc1k\x7f\xce" +
	"[c\xf7J\xbc\x14$U\xbb\xd8\x19\x86Zi>X" +
	"\xb0\x8f\x05\x18Jja\x1c1\x0b\xc5\xacx8\xb7\x10" +
	"\x87\xe5\x09dmm\xbe=\x7f\xff\x05\x00\x00\xff\xff\xbe" +
	"\x90G@"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_da3a0d9284ca402f,
		Nodes: []uint64{
			0x922b57c60c6a46d1,
			0xa4b9c59286b69600,
			0xcb5ff253617678e0,
		},
		Compressed: true,
	})
}
