// Code generated by capnpc-go. DO NOT EDIT.

package main

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
)

type Way capnp.Struct

// Way_TypeID is the unique identifier for the type Way.
const Way_TypeID = 0xa4b9c59286b69600

func NewWay(s *capnp.Segment) (Way, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 72, PointerCount: 4})
	return Way(st), err
}

func NewRootWay(s *capnp.Segment) (Way, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 72, PointerCount: 4})
	return Way(st), err
}

func ReadRootWay(msg *capnp.Message) (Way, error) {
	root, err := msg.Root()
	return Way(root.Struct()), err
}

func (s Way) String() string {
	str, _ := text.Marshal(0xa4b9c59286b69600, capnp.Struct(s))
	return str
}

func (s Way) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Way) DecodeFromPtr(p capnp.Ptr) Way {
	return Way(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Way) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Way) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Way) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Way) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Way) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Way) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Way) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Way) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Way) Ref() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Way) HasRef() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Way) RefBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Way) SetRef(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Way) MaxSpeed() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Way) SetMaxSpeed(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Way) MinLat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Way) SetMinLat(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s Way) MinLon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(16))
}

func (s Way) SetMinLon(v float64) {
	capnp.Struct(s).SetUint64(16, math.Float64bits(v))
}

func (s Way) MaxLat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(24))
}

func (s Way) SetMaxLat(v float64) {
	capnp.Struct(s).SetUint64(24, math.Float64bits(v))
}

func (s Way) MaxLon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(32))
}

func (s Way) SetMaxLon(v float64) {
	capnp.Struct(s).SetUint64(32, math.Float64bits(v))
}

func (s Way) Nodes() (Coordinates_List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return Coordinates_List(p.List()), err
}

func (s Way) HasNodes() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Way) SetNodes(v Coordinates_List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewNodes sets the nodes field to a newly
// allocated Coordinates_List, preferring placement in s's segment.
func (s Way) NewNodes(n int32) (Coordinates_List, error) {
	l, err := NewCoordinates_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Coordinates_List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s Way) Lanes() uint8 {
	return capnp.Struct(s).Uint8(40)
}

func (s Way) SetLanes(v uint8) {
	capnp.Struct(s).SetUint8(40, v)
}

func (s Way) AdvisorySpeed() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(48))
}

func (s Way) SetAdvisorySpeed(v float64) {
	capnp.Struct(s).SetUint64(48, math.Float64bits(v))
}

func (s Way) Hazard() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Way) HasHazard() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Way) HazardBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Way) SetHazard(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Way) OneWay() bool {
	return capnp.Struct(s).Bit(328)
}

func (s Way) SetOneWay(v bool) {
	capnp.Struct(s).SetBit(328, v)
}

func (s Way) MaxSpeedForward() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(56))
}

func (s Way) SetMaxSpeedForward(v float64) {
	capnp.Struct(s).SetUint64(56, math.Float64bits(v))
}

func (s Way) MaxSpeedBackward() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(64))
}

func (s Way) SetMaxSpeedBackward(v float64) {
	capnp.Struct(s).SetUint64(64, math.Float64bits(v))
}

func (s Way) WindingForwardLevel() uint8 {
	return capnp.Struct(s).Uint8(42)
}

func (s Way) SetWindingForwardLevel(v uint8) {
	capnp.Struct(s).SetUint8(42, v)
}

func (s Way) WindingBackwardLevel() uint8 {
	return capnp.Struct(s).Uint8(43)
}

func (s Way) SetWindingBackwardLevel(v uint8) {
	capnp.Struct(s).SetUint8(43, v)
}

func (s Way) WindingForwardScore() uint8 {
	return capnp.Struct(s).Uint8(44)
}

func (s Way) SetWindingForwardScore(v uint8) {
	capnp.Struct(s).SetUint8(44, v)
}

func (s Way) WindingBackwardScore() uint8 {
	return capnp.Struct(s).Uint8(45)
}

func (s Way) SetWindingBackwardScore(v uint8) {
	capnp.Struct(s).SetUint8(45, v)
}

func (s Way) WindingForwardConfidence() uint8 {
	return capnp.Struct(s).Uint8(46)
}

func (s Way) SetWindingForwardConfidence(v uint8) {
	capnp.Struct(s).SetUint8(46, v)
}

func (s Way) WindingBackwardConfidence() uint8 {
	return capnp.Struct(s).Uint8(47)
}

func (s Way) SetWindingBackwardConfidence(v uint8) {
	capnp.Struct(s).SetUint8(47, v)
}

// Way_List is a list of Way.
type Way_List = capnp.StructList[Way]

// NewWay creates a new list of Way.
func NewWay_List(s *capnp.Segment, sz int32) (Way_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 72, PointerCount: 4}, sz)
	return capnp.StructList[Way](l), err
}

// Way_Future is a wrapper for a Way promised by a client call.
type Way_Future struct{ *capnp.Future }

func (f Way_Future) Struct() (Way, error) {
	p, err := f.Future.Ptr()
	return Way(p.Struct()), err
}

type Coordinates capnp.Struct

// Coordinates_TypeID is the unique identifier for the type Coordinates.
const Coordinates_TypeID = 0x922b57c60c6a46d1

func NewCoordinates(s *capnp.Segment) (Coordinates, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Coordinates(st), err
}

func NewRootCoordinates(s *capnp.Segment) (Coordinates, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Coordinates(st), err
}

func ReadRootCoordinates(msg *capnp.Message) (Coordinates, error) {
	root, err := msg.Root()
	return Coordinates(root.Struct()), err
}

func (s Coordinates) String() string {
	str, _ := text.Marshal(0x922b57c60c6a46d1, capnp.Struct(s))
	return str
}

func (s Coordinates) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Coordinates) DecodeFromPtr(p capnp.Ptr) Coordinates {
	return Coordinates(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Coordinates) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Coordinates) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Coordinates) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Coordinates) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Coordinates) Latitude() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Coordinates) SetLatitude(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Coordinates) Longitude() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Coordinates) SetLongitude(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

// Coordinates_List is a list of Coordinates.
type Coordinates_List = capnp.StructList[Coordinates]

// NewCoordinates creates a new list of Coordinates.
func NewCoordinates_List(s *capnp.Segment, sz int32) (Coordinates_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[Coordinates](l), err
}

// Coordinates_Future is a wrapper for a Coordinates promised by a client call.
type Coordinates_Future struct{ *capnp.Future }

func (f Coordinates_Future) Struct() (Coordinates, error) {
	p, err := f.Future.Ptr()
	return Coordinates(p.Struct()), err
}

type Offline capnp.Struct

// Offline_TypeID is the unique identifier for the type Offline.
const Offline_TypeID = 0xcb5ff253617678e0

func NewOffline(s *capnp.Segment) (Offline, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 1})
	return Offline(st), err
}

func NewRootOffline(s *capnp.Segment) (Offline, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 1})
	return Offline(st), err
}

func ReadRootOffline(msg *capnp.Message) (Offline, error) {
	root, err := msg.Root()
	return Offline(root.Struct()), err
}

func (s Offline) String() string {
	str, _ := text.Marshal(0xcb5ff253617678e0, capnp.Struct(s))
	return str
}

func (s Offline) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Offline) DecodeFromPtr(p capnp.Ptr) Offline {
	return Offline(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Offline) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Offline) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Offline) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Offline) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Offline) MinLat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Offline) SetMinLat(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Offline) MinLon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Offline) SetMinLon(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s Offline) MaxLat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(16))
}

func (s Offline) SetMaxLat(v float64) {
	capnp.Struct(s).SetUint64(16, math.Float64bits(v))
}

func (s Offline) MaxLon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(24))
}

func (s Offline) SetMaxLon(v float64) {
	capnp.Struct(s).SetUint64(24, math.Float64bits(v))
}

func (s Offline) Ways() (Way_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Way_List(p.List()), err
}

func (s Offline) HasWays() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Offline) SetWays(v Way_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewWays sets the ways field to a newly
// allocated Way_List, preferring placement in s's segment.
func (s Offline) NewWays(n int32) (Way_List, error) {
	l, err := NewWay_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Way_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s Offline) Overlap() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(32))
}

func (s Offline) SetOverlap(v float64) {
	capnp.Struct(s).SetUint64(32, math.Float64bits(v))
}

// Offline_List is a list of Offline.
type Offline_List = capnp.StructList[Offline]

// NewOffline creates a new list of Offline.
func NewOffline_List(s *capnp.Segment, sz int32) (Offline_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 40, PointerCount: 1}, sz)
	return capnp.StructList[Offline](l), err
}

// Offline_Future is a wrapper for a Offline promised by a client call.
type Offline_Future struct{ *capnp.Future }

func (f Offline_Future) Struct() (Offline, error) {
	p, err := f.Future.Ptr()
	return Offline(p.Struct()), err
}

const schema_da3a0d9284ca402f = "x\xda\xa4\xd4\xcfk\x1ce\x18\x07\xf0\xef\xf7\x99\xc9n" +
	"\xd2\xfc\xd8l\xdf9x\xa8D\xc5B\x92\xa6m\xa2\x11" +
	"j\x884\xa6\x12\xa4\x04\xcc8H*\x14\xf4e\xe7\xdd" +
	"du3\x137k~\x08b\x15\x15\x94z0\xa8D" +
	"Phe\x05\x15\x05\x11\x11=\x14z\xa8\x1e\xeaE{" +
	"\xf4\xe4\xdf\xe0\x1f\xe0\xca3\x9b\xfdQ\xad\xa7\xdef>" +
	"\xcf\x8f\xf7e\xf7yf\xfaAY\xf0g\x86S\x81\x84" +
	"\xc7\xfar\xcd\xdf\x97^\x18\xfae\xf5\xc4>\xc2\x11J" +
	"\xf3\xf4\xc2\xcd7\xf7\x87\xe7\xfe\x80\x9f\x07\xcc\xbd\xbce" +
	"&\xa8O\xc7\xb9\x03\xfe\xfd\xd1\x0fo\xef\xff\xfcS#" +
	"\x1c\xe1@7\xb3/K}\x87\xfb\xe6}M}\xf8=" +
	"\xae\xf9`\xf3\xcf\xddm\x1b\xfd\xf5\xdc\xaf\xda\xb7\xaf'" +
	";k\xf7j\xee;\xf3VN\xb3_\xcf\xad\x12'\x9b" +
	"i\xb9\\\xad$\xee\x94\x94\xecf\xb29w.Mk" +
	"q%\xb1u\xc7\xad\x152\xec\xf7|\xc0'P\x9c8" +
	"\x0f\x84\xe3\x1e\xc3Ya\x91\x0c\xa88\xf34\x10N{" +
	"\x0c\xe7\x85\xcd\xaa\xadW\xea/\xc7\x0e\x00\x07!\x1c\x04" +
	"\x9b\xd54YS\x04]\xc7\xdaG\xb2u\xe4\xaa\xe5\x9e" +
	"\x1e\xb5\xd2>\xca\xdc/\x93@tL<F\xe3\xd2=" +
	"\xcd\x1c\x97\x07\x80\xe8>\xf5)\x11R\x02\x0a`&\xe4" +
	"<\x10\x8d+\xcfj\xba\xc7\x80\x1e`fd\x0e\x88\xa6" +
	"\xd4\xcf\xa8\xfb\x12\xd0\x07\xcc#\x99O\xab\xcf\xab\xf7y" +
	"\x01\xfb\x00\xf3h\xe6\xb3\xea\x0b\xea9?`\x0e0\x8f" +
	"e~F\xfd\x09\xf5\xbc\x04\xd9o\xf9\xb8<\x04D\xf3" +
	"\xea\x17\xd4\xfb\xc7\x03\xf6\x03\xe6\x99\xccW\xd4/\xaa\x0f" +
	"\xe4\x02\x0e\x00\xe6Y\xa9\x01\xd1\x05\xf5X\xfd\x88\x17\xf0" +
	"\x08`l\xd6\xff\xa2\xfa\xba\x08g\x06\x9fd\xc0A\xc0" +
	"\xb8,\xf0\xbc\x06\xaaZ0\x94\x0f8\x04\x98\x8a\xbc\x01" +
	"D\xeb\xeau\xf5\xe1\xfe\x80\xc3\x80yI\xde\x05\xa2\xba" +
	"\xfa%\xf5\x91\xc9\x80#\xfa\xa7\xcbg@tI\xfd\xb2" +
	"z\xe1D\xc0\x82\x8e\x8e|\x05D\x97\xd5\x0f\xd4G\xa7" +
	"\x02\x8e\x02\xe6\xc3,\xff@\xbd\xa1^<\x19\xb0\x08\x98" +
	"\xabY~C\xfd[\xf5\xa3\xa7\x02\x1e\x05\xcc7r\x13" +
	"\x88\xbeW\xbf\xaenN\x074\x80\xb9&\xb7\x80\xe8\x86" +
	"\xfao\",$v\xc3q\x08\xc2!0_s\xe5\xf6" +
	"ss\xc3\xeeF\x9b\xce\xc5=\x93sv\xa3\x92,\xdb" +
	"\xfam\xafi\xd2}\xb5\xbb\xb7E\xednOt,I" +
	"c\xb7\xc5\x11p\xc5#G\xbb\x9b\x06*\x8eUm\xe2" +
	"\xb6\x98\x830\x076m\xbc]\xd9Jk{\x18\xcb\xee" +
	"\xd0\xe9\xb9n_\xb1\xb5\xb8}\xc7\xb3i\xe2V\xed\x1e" +
	"\x09!{\xae\xcc\xa5\xb4\xb6ckqw\xe4;\x91E" +
	"[z1\x0buc;\x95$\xae$kKl\x15-" +
	"\xbb\xfc\xb6\xabvnr\x18]\xe4a\xe1r\xc1\xdd!" +
	"\xdc.\x8eJ\xf9\xb4\xe6\xfe\xb78*\x94\xee\x10^\x92" +
	"V\xf1\xb94)Wb\x97\x94\x1c\xf0\x9f\x16r\xd8\xa2" +
	"\x93\xc4n\x9f\x7f-\xefS\xe5\xb1\xec]\x17\xf8\x9e\xce" +
	"\xb7\xe2\xe39 \xfc\xc0cx\xa5\xe7[\xf1\xa9\xe2\x81" +
	"\xc7\xb0!,Jkw\x8bW\x15?\xf1\x18~\xa1\x8b" +
	"\xebe\x8b[\xfc\\\xf1\x8a\xc7\xf0k!\xfdli\x8b" +
	"_N\x02a\xc3cx]7\xd6\xcf6\xb6xm\x11" +
	"\x08\x7f\xf4\x18\xde\x90\xbb\x1a\x98\xc2\x8e\xdd\xeb\xceK\xfb" +
	"k\xdb\x9a\x96\xd7\xd2mW\xab\xda\xcdv\xee?\x01\x00" +
	"\x00\xff\xff\xf1p!+"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_da3a0d9284ca402f,
		Nodes: []uint64{
			0x922b57c60c6a46d1,
			0xa4b9c59286b69600,
			0xcb5ff253617678e0,
		},
		Compressed: true,
	})
}
