#pragma once

#include <string>
#include <unordered_map>

#include "cereal/gen/cpp/log.capnp.h"

inline static std::unordered_map<std::string, ParamKeyAttributes> keys = {
    {"AccessToken", {CLEAR_ON_MANAGER_START | DONT_LOG, STRING}},
    {"AdbEnabled", {PERSISTENT | BACKUP, BOOL}},
    {"AlwaysOnDM", {PERSISTENT | BACKUP, BOOL}},
    {"ApiCache_Device", {PERSISTENT, STRING}},
    {"ApiCache_FirehoseStats", {PERSISTENT, JSON}},
    {"AssistNowToken", {PERSISTENT, STRING}},
    {"AthenadPid", {PERSISTENT, INT}},
    {"AthenadUploadQueue", {PERSISTENT, JSON}},
    {"AthenadRecentlyViewedRoutes", {PERSISTENT, STRING}},
    {"BootCount", {PERSISTENT, INT}},
    {"CalibrationParams", {PERSISTENT, BYTES}},
    {"CameraDebugExpGain", {CLEAR_ON_MANAGER_START, STRING}},
    {"CameraDebugExpTime", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarBatteryCapacity", {PERSISTENT, INT}},
    {"CarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsPersistent", {PERSISTENT, BYTES}},
    {"CarParamsPrevRoute", {PERSISTENT, BYTES}},
    {"CompletedTrainingVersion", {PERSISTENT, STRING, "0"}},
    {"ControlsReady", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"CurrentBootlog", {PERSISTENT, STRING}},
    {"CurrentRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"DisableLogging", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"DisablePowerDown", {PERSISTENT | BACKUP, BOOL}},
    {"DisableUpdates", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"DisengageOnAccelerator", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"DongleId", {PERSISTENT, STRING}},
    {"DoReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoShutdown", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUninstall", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DriverTooDistracted", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"AlphaLongitudinalEnabled", {PERSISTENT | DEVELOPMENT_ONLY | BACKUP, BOOL}},
    {"ExperimentalMode", {PERSISTENT | BACKUP, BOOL}},
    {"ExperimentalModeConfirmed", {PERSISTENT | BACKUP, BOOL}},
    {"FirmwareQueryDone", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ForcePowerDown", {PERSISTENT, BOOL}},
    {"GitBranch", {PERSISTENT, STRING}},
    {"GitCommit", {PERSISTENT, STRING}},
    {"GitCommitDate", {PERSISTENT, STRING}},
    {"GitDiff", {PERSISTENT, STRING}},
    {"GithubSshKeys", {PERSISTENT | BACKUP, STRING}},
    {"GithubUsername", {PERSISTENT | BACKUP, STRING}},
    {"GitRemote", {PERSISTENT, STRING}},
    {"GsmApn", {PERSISTENT | BACKUP, STRING}},
    {"GsmMetered", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"GsmRoaming", {PERSISTENT | BACKUP, BOOL}},
    {"HardwareSerial", {PERSISTENT, STRING}},
    {"HasAcceptedTerms", {PERSISTENT, STRING, "0"}},
    {"InstallDate", {PERSISTENT, TIME}},
    {"IsDriverViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsEngaged", {PERSISTENT, BOOL}},
    {"IsLdwEnabled", {PERSISTENT | BACKUP, BOOL}},
    {"IsMetric", {PERSISTENT | BACKUP, BOOL}},
    {"IsOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsOnroad", {PERSISTENT, BOOL}},
    {"IsRhdDetected", {PERSISTENT, BOOL}},
    {"IsReleaseBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTakingSnapshot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTestedBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"JoystickDebugMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LanguageSetting", {PERSISTENT | BACKUP, STRING, "main_en"}},
    {"LastAthenaPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"LastGPSPosition", {PERSISTENT, STRING}},
    {"LastManagerExitReason", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastOffroadStatusPacket", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON}},
    {"LastPowerDropDetected", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateException", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateRouteCount", {PERSISTENT, INT}},
    {"LastUpdateTime", {PERSISTENT, TIME}},
    {"LastUpdateUptimeOnroad", {PERSISTENT, FLOAT}},
    {"LiveDelay", {PERSISTENT | BACKUP, BYTES}},
    {"LiveParameters", {PERSISTENT, JSON}},
    {"LiveParametersV2", {PERSISTENT, BYTES}},
    {"LiveTorqueParameters", {PERSISTENT | DONT_LOG, BYTES}},
    {"LocationFilterInitialState", {PERSISTENT, BYTES}},
    {"LongitudinalManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalPersonality", {PERSISTENT | BACKUP, INT, std::to_string(static_cast<int>(cereal::LongitudinalPersonality::STANDARD))}},
    {"NetworkMetered", {PERSISTENT | BACKUP, BOOL}},
    {"ObdMultiplexingChanged", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ObdMultiplexingEnabled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"Offroad_CarUnrecognized", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ConnectivityNeeded", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeededPrompt", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ExcessiveActuation", {PERSISTENT, JSON}},
    {"Offroad_IsTakingSnapshot", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NeosUpdate", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NoFirmware", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_Recalibration", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_StorageMissing", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_TemperatureTooHigh", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UnregisteredHardware", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UpdateFailed", {CLEAR_ON_MANAGER_START, JSON}},
    {"OnroadCycleRequested", {CLEAR_ON_MANAGER_START, BOOL}},
    {"OpenpilotEnabledToggle", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"PandaHeartbeatLost", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSomResetTriggered", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSignatures", {CLEAR_ON_MANAGER_START, BYTES}},
    {"PrimeType", {PERSISTENT, INT}},
    {"RecordAudio", {PERSISTENT | BACKUP, BOOL}},
    {"RecordAudioFeedback", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"RecordFront", {PERSISTENT | BACKUP, BOOL}},
    {"RecordFrontLock", {PERSISTENT, BOOL}},  // for the internal fleet
    {"SecOCKey", {PERSISTENT | DONT_LOG | BACKUP, STRING}},
    {"RouteCount", {PERSISTENT, INT, "0"}},
    {"SnoozeUpdate", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SshEnabled", {PERSISTENT | BACKUP, BOOL}},
    {"TermsVersion", {PERSISTENT, STRING}},
    {"TrainingVersion", {PERSISTENT, STRING}},
    {"UbloxAvailable", {PERSISTENT, BOOL}},
    {"UpdateAvailable", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"UpdateFailedCount", {CLEAR_ON_MANAGER_START, INT}},
    {"UpdaterAvailableBranches", {PERSISTENT, STRING}},
    {"UpdaterCurrentDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterCurrentReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterFetchAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UpdaterNewDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterNewReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterState", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterTargetBranch", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterLastFetchTime", {PERSISTENT, TIME}},
    {"UptimeOffroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"Version", {PERSISTENT, STRING}},

    // --- sunnypilot params --- //
    {"AccelPersonality", {PERSISTENT, STRING, "1"}},
    {"ApiCache_DriveStats", {PERSISTENT, JSON}},
    {"AutoLaneChangeBsmDelay", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"AutoLaneChangeTimer", {PERSISTENT | BACKUP, INT, "0"}},
    {"BlindSpot", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"BlinkerMinLateralControlSpeed", {PERSISTENT | BACKUP, INT, "20"}},  // MPH or km/h
    {"BlinkerPauseLateralControl", {PERSISTENT | BACKUP, INT, "0"}},
    {"Brightness", {PERSISTENT | BACKUP, INT, "0"}},
    {"CarParamsSP", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsSPCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsSPPersistent", {PERSISTENT, BYTES}},
    {"CarPlatformBundle", {PERSISTENT | BACKUP, JSON}},
    {"ChevronInfo", {PERSISTENT | BACKUP, INT, "4"}},
    {"CustomAccIncrementsEnabled", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"CustomAccLongPressIncrement", {PERSISTENT | BACKUP, INT, "5"}},
    {"CustomAccShortPressIncrement", {PERSISTENT | BACKUP, INT, "1"}},
    {"DeviceBootMode", {PERSISTENT | BACKUP, INT, "0"}},
    {"EnableGithubRunner", {PERSISTENT | BACKUP, BOOL}},
    {"GithubRunnerSufficientVoltage", {CLEAR_ON_MANAGER_START , BOOL}},
    {"GithubRunnerVoltage", {PERSISTENT | BACKUP, BOOL}},
    {"InteractivityTimeout", {PERSISTENT | BACKUP, INT, "0"}},
    {"IsDevelopmentBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsMetricDistance", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"MaxTimeOffroad", {PERSISTENT | BACKUP, INT, "1800"}},
    {"ModelRunnerTypeCache", {CLEAR_ON_ONROAD_TRANSITION, INT}},
    {"OffroadMode", {CLEAR_ON_MANAGER_START, BOOL}},
    // Developer-only ignition override to force onroad for debugging
    {"ForceOnroad", {CLEAR_ON_MANAGER_START | DEVELOPMENT_ONLY, BOOL}},
    {"QuickBootToggle", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"QuietMode", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"RainbowMode", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"ShowAdvancedControls", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"VisionTurnSpeedControl", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"VTSCRallyCoPilotHUDEnabled", {PERSISTENT | BACKUP, BOOL, "0"}},
    // Aggressiveness multiplier for anticipatory slowing before curves (legacy default = 1)
    {"VisionTurnSpeedControlAggressiveness", {PERSISTENT | BACKUP, INT, "1"}},
    // Optional fixed lead time override in seconds (0 = disabled, use automatic timing)
    {"VisionTurnSpeedControlFixedLeadTimeSeconds", {PERSISTENT | BACKUP, FLOAT, "0.0"}},
    // Signed timing offsets (seconds): 0 = default; lower starts earlier, higher starts later
    {"VisionTurnSpeedControlCurvePhaseOffsetS", {PERSISTENT | BACKUP, FLOAT, "0.0"}},
    {"VisionTurnSpeedControlOvershootPhaseOffsetS", {PERSISTENT | BACKUP, FLOAT, "0.0"}},
    {"VisionTurnSpeedControlApexExitPhaseOffsetS", {PERSISTENT | BACKUP, FLOAT, "0.0"}},

    // VTSC Adaptive Deceleration Parameters
    {"VisionTurnSpeedControlFilterAlpha", {PERSISTENT | BACKUP, FLOAT, "0.3"}},
    {"VisionTurnSpeedControlHysteresisThreshold", {PERSISTENT | BACKUP, FLOAT, "0.2"}},
    {"VisionTurnSpeedControlSafetyBias", {PERSISTENT | BACKUP, FLOAT, "0.1"}},

    // VTSC Smoothing & Limits
    {"VisionTurnSpeedControlCurvatureEMAFactor", {PERSISTENT | BACKUP, FLOAT, "0.3"}},
    {"VisionTurnSpeedControlSmoothingMaxDecel", {PERSISTENT | BACKUP, FLOAT, "3.5"}},
    {"VisionTurnSpeedControlSmoothingMaxJerk", {PERSISTENT | BACKUP, FLOAT, "6.0"}},
    {"VisionTurnSpeedControlAccelToDecelRatio", {PERSISTENT | BACKUP, FLOAT, "1.3"}},
    {"VisionTurnSpeedControlJerkAccelMultiplier", {PERSISTENT | BACKUP, FLOAT, "2.0"}},

    // VTSC Planning & Safety
    {"VisionTurnSpeedControlPlanningDecelLimit", {PERSISTENT | BACKUP, FLOAT, "3.5"}},
    {"VisionTurnSpeedControlOvershootSafetyMargin", {PERSISTENT | BACKUP, FLOAT, "1.2"}},
    {"VisionTurnSpeedControlOvershootMinDistance", {PERSISTENT | BACKUP, FLOAT, "10.0"}},
    {"VisionTurnSpeedControlAnticipationTargetReduction", {PERSISTENT | BACKUP, FLOAT, "0.95"}},

    // VTSC Apex Detection & Boost
    {"VisionTurnSpeedControlApexThreshold", {PERSISTENT | BACKUP, FLOAT, "0.00005"}},
    {"VisionTurnSpeedControlApexProminence", {PERSISTENT | BACKUP, FLOAT, "0.0001"}},
    {"VisionTurnSpeedControlApexHysteresisTime", {PERSISTENT | BACKUP, FLOAT, "2.0"}},
    {"VisionTurnSpeedControlApexMetersPerIndex", {PERSISTENT | BACKUP, FLOAT, "2.0"}},
    {"VisionTurnSpeedControlApexNearIndex", {PERSISTENT | BACKUP, INT, "3"}},
    {"VisionTurnSpeedControlApexBoostDistance", {PERSISTENT | BACKUP, FLOAT, "50.0"}},
    {"VisionTurnSpeedControlApexBoostFactor", {PERSISTENT | BACKUP, FLOAT, "0.1"}},
    {"VisionTurnSpeedControlApexBoostMinLatAccel", {PERSISTENT | BACKUP, FLOAT, "1.0"}},
    {"VisionTurnSpeedControlApexBoostCenter", {PERSISTENT | BACKUP, FLOAT, "2.0"}},
    {"VisionTurnSpeedControlApexBoostWidth", {PERSISTENT | BACKUP, FLOAT, "0.5"}},
    {"VisionTurnSpeedControlBoostSafetyCurvatureScale", {PERSISTENT | BACKUP, FLOAT, "0.7"}},

    // VTSC Comfort Limits
    {"VisionTurnSpeedControlComfortDecelLimit", {PERSISTENT | BACKUP, FLOAT, "-1.47"}},
    {"VisionTurnSpeedControlComfortJerkLimit", {PERSISTENT | BACKUP, FLOAT, "-2.0"}},
    {"VisionTurnSpeedControlMaxAdaptiveDecel", {PERSISTENT | BACKUP, FLOAT, "-6.0"}},
    {"VisionTurnSpeedControlMaxAdaptiveJerk", {PERSISTENT | BACKUP, FLOAT, "-6.0"}},

    // VTSC Vision Confidence
    {"VisionTurnSpeedControlVisionConfAlpha", {PERSISTENT | BACKUP, FLOAT, "0.28"}},
    {"VisionTurnSpeedControlVisionConfGoodThreshold", {PERSISTENT | BACKUP, FLOAT, "0.70"}},
    {"VisionTurnSpeedControlVisionConfBadThreshold", {PERSISTENT | BACKUP, FLOAT, "0.65"}},

    // VTSC Occlusion dwell & decay tunables

    // VTSC Occlusion Handling
    {"VisionTurnSpeedControlOcclEnterDwellS", {PERSISTENT | BACKUP, FLOAT, "0.20"}},
    {"VisionTurnSpeedControlOcclExitDwellS", {PERSISTENT | BACKUP, FLOAT, "0.10"}},
    {"VisionTurnSpeedControlCurvatureGrowthPerMeter", {PERSISTENT | BACKUP, FLOAT, "0.0005"}},
    {"VisionTurnSpeedControlEnvelopeHorizonS", {PERSISTENT | BACKUP, FLOAT, "1.2"}},
    {"VisionTurnSpeedControlOcclusionDecayTauFastS", {PERSISTENT | BACKUP, FLOAT, "1.2"}},
    {"VisionTurnSpeedControlOcclusionDecayTauSlowS", {PERSISTENT | BACKUP, FLOAT, "2.0"}},
    {"VisionTurnSpeedControlOcclusionMinFrac", {PERSISTENT | BACKUP, FLOAT, "0.20"}},
    {"VisionTurnSpeedControlFastReacqAlpha", {PERSISTENT | BACKUP, FLOAT, "0.85"}},
    {"VisionTurnSpeedControlFastReacqWindowS", {PERSISTENT | BACKUP, FLOAT, "0.90"}},

    // VTSC Visibility barrier params
    {"VisionTurnSpeedControlVisHorizonS", {PERSISTENT | BACKUP, FLOAT, "1.4"}},
    {"VisionTurnSpeedControlVisMarginM", {PERSISTENT | BACKUP, FLOAT, "10.0"}},
    {"VisionTurnSpeedControlGammaPerMeter", {PERSISTENT | BACKUP, FLOAT, "0.00035"}},
    {"VisionTurnSpeedControlLatJerkCap", {PERSISTENT | BACKUP, FLOAT, "2.0"}},

    // VTSC Field-of-View (FOV) gating + geometry
    {"VisionTurnSpeedControlPsiFOVRad", {PERSISTENT | BACKUP, FLOAT, "0.49"}},
    {"VisionTurnSpeedControlPsiMarginRad", {PERSISTENT | BACKUP, FLOAT, "0.087"}},
    {"VisionTurnSpeedControlFOVKMin", {PERSISTENT | BACKUP, FLOAT, "0.0002"}},
    {"VisionTurnSpeedControlFOVKFreeway", {PERSISTENT | BACKUP, FLOAT, "0.00001"}},
    {"VisionTurnSpeedControlFOVSLongM", {PERSISTENT | BACKUP, FLOAT, "120.0"}},
    {"VisionTurnSpeedControlFOVPretriggerTimeS", {PERSISTENT | BACKUP, FLOAT, "1.2"}},
    {"VisionTurnSpeedControlFOVOnsetBoostFrames", {PERSISTENT | BACKUP, INT, "10"}},

    // --- Bluetooth (Offroad Network → Bluetooth) --- //
    {"BluetoothEnabled", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"BluetoothDiscoverable", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"VisionTurnSpeedControlFOVOvershootFrames", {PERSISTENT | BACKUP, INT, "10"}},
    {"VisionTurnSpeedControlFOVEWMATauS", {PERSISTENT | BACKUP, FLOAT, "0.5"}},
    {"VisionTurnSpeedControlFOVNOn", {PERSISTENT | BACKUP, INT, "5"}},
    {"VisionTurnSpeedControlFOVNOff", {PERSISTENT | BACKUP, INT, "10"}},

    // VTSC Vision-floor and dropout discrimination
    // Seconds to retain last-known-good vision floor
    {"VisionTurnSpeedControlVisionFloorTtlS", {PERSISTENT | BACKUP, FLOAT, "3.0"}},
    // Multiplier applied to the floor speed cap
    {"VisionTurnSpeedControlVisionFloorMult", {PERSISTENT | BACKUP, FLOAT, "1.0"}},
    // Grace period for transient model dropouts (seconds)
    {"VisionTurnSpeedControlDropoutGraceS", {PERSISTENT | BACKUP, FLOAT, "0.40"}},

    // VTSC Speed Control
    {"VisionTurnSpeedControlSpeedIncreaseFactor", {PERSISTENT | BACKUP, FLOAT, "1.0"}},
    {"VisionTurnSpeedControlMaxSpeed", {PERSISTENT | BACKUP, FLOAT, "70.0"}},
    {"VisionTurnSpeedControlMinOperatingSpeed", {PERSISTENT | BACKUP, FLOAT, "2.24"}},
    {"VisionTurnSpeedControlLowSpeedSpeedBiasMph", {PERSISTENT | BACKUP, FLOAT, "0.0"}},
    {"VisionTurnSpeedControlLowSpeedBiasEndMph", {PERSISTENT | BACKUP, FLOAT, "50.0"}},

    // VTSC Physics Model
    {"VisionTurnSpeedControlPhysicsBaseline", {PERSISTENT | BACKUP, FLOAT, "3.144734"}},
    {"VisionTurnSpeedControlPhysicsAmplitude", {PERSISTENT | BACKUP, FLOAT, "-1.1751"}},
    {"VisionTurnSpeedControlPhysicsSteepness", {PERSISTENT | BACKUP, FLOAT, "-2000.0"}},
    {"VisionTurnSpeedControlPhysicsCenter", {PERSISTENT | BACKUP, FLOAT, "0.004778"}},
    {"VisionTurnSpeedControlPhysicsMinLatAccel", {PERSISTENT | BACKUP, FLOAT, "1.8"}},
    {"VisionTurnSpeedControlPhysicsMaxLatAccel", {PERSISTENT | BACKUP, FLOAT, "3.12"}},
    
    // MTSC (Map Turn Speed Control) debug + profiling
    {"MTSCEnabled", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"MTSCLogDetail", {PERSISTENT | BACKUP, INT, "0"}},
    {"MTSCNearbyLimit", {PERSISTENT | BACKUP, INT, "10"}},
    {"MTSCProfile", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"MTSCRealtime", {PERSISTENT | BACKUP, BOOL, "0"}},
    
    {"VibePersonalityEnabled", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"VibeAccelPersonalityEnabled", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"VibeFollowPersonalityEnabled", {PERSISTENT | BACKUP, BOOL, "0"}},

    // MADS params
    {"Mads", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"MadsMainCruiseAllowed", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"MadsSteeringMode", {PERSISTENT | BACKUP, INT, "0"}},
    {"MadsUnifiedEngagementMode", {PERSISTENT | BACKUP, BOOL, "1"}},

    // Model Manager params
    {"DynamicModeldOutputs", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"ModelManager_ActiveBundle", {PERSISTENT, JSON}},
    {"ModelManager_ClearCache", {CLEAR_ON_MANAGER_START, BOOL}},
    {"ModelManager_DownloadIndex", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, INT, "0"}},
    {"ModelManager_LastSyncTime", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, INT, "0"}},
    {"ModelManager_ModelsCache", {PERSISTENT | BACKUP, JSON}},

    // Neural Network Lateral Control
    {"NeuralNetworkLateralControl", {PERSISTENT | BACKUP, BOOL, "0"}},

    // sunnylink params
    {"EnableSunnylinkUploader", {PERSISTENT | BACKUP, BOOL}},
    {"LastSunnylinkPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"SunnylinkCache_Roles", {PERSISTENT, STRING}},
    {"SunnylinkCache_Users", {PERSISTENT, STRING}},
    {"SunnylinkDongleId", {PERSISTENT, STRING}},
    {"SunnylinkdPid", {PERSISTENT, INT}},
    {"SunnylinkEnabled", {PERSISTENT, BOOL}},

    // Backup Manager params
    {"BackupManager_CreateBackup", {PERSISTENT, BOOL}},
    {"BackupManager_RestoreVersion", {PERSISTENT, STRING}},

    // sunnypilot car specific params
    {"HyundaiLongitudinalTuning", {PERSISTENT | BACKUP, INT, "0"}},

    // Hyundai Longitudinal Tuning Live Parameters
    {"LiveSteerRatio", {PERSISTENT | BACKUP, FLOAT, "0"}},
    {"LongTuningCustomToggle", {PERSISTENT | BACKUP, INT, "0"}},
    {"LongTuningAccelMin", {PERSISTENT | BACKUP, FLOAT, "-3.5"}},
    {"LongTuningAccelMax", {PERSISTENT | BACKUP, FLOAT, "2.0"}},
    {"LongTuningVEgoStopping", {PERSISTENT | BACKUP, FLOAT, ".25"}},
    {"LongTuningStoppingDecelRate", {PERSISTENT | BACKUP, FLOAT, ".40"}},
    {"LongTuningJerkLimits", {PERSISTENT | BACKUP, FLOAT, "4.0"}},
    {"LongTuningMinUpperJerk", {PERSISTENT | BACKUP, FLOAT, ".5"}},
    {"LongTuningMinLowerJerk", {PERSISTENT | BACKUP, FLOAT, ".5"}},

    // Dynamic Experimental Controller
    {"DynamicExperimentalControl", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"DynamicExperimentalStandstill", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"DynamicExperimentalModelSlowDown", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"DynamicExperimentalFCW", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"DynamicExperimentalHasLead", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"DynamicExperimentalDistanceBased", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"DynamicExperimentalDistanceValue", {PERSISTENT | BACKUP, FLOAT, "30"}},
    {"DynamicExperimentalSpeedBased", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"DynamicExperimentalSpeedValue", {PERSISTENT | BACKUP, FLOAT, "25"}},
    {"DynamicExperimentalFollowLead", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"DynamicExperimentalSlowerLead", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"DynamicExperimentalStoppedLead", {PERSISTENT | BACKUP, BOOL, "0"}},

    // model panel params
    {"LagdToggle", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"LagdToggleDelay", {PERSISTENT | BACKUP, FLOAT, "0.2"}},
    {"LagdValueCache", {PERSISTENT, FLOAT, "0.2"}},

    // mapd + MTSC
    {"MapAdvisorySpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, FLOAT}},
    {"MapCurvatures", {CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"MapHazard", {CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"MapdVersion", {PERSISTENT, STRING, ""}},
    {"MapSpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, FLOAT, "0.0"}},
    {"MapTargetLatA", {CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"MapTargetVelocities", {CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"NextMapAdvisoryLimit", {CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"NextMapHazard", {CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"NextMapSpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_OSMUpdateRequired", {CLEAR_ON_MANAGER_START, JSON}},
    {"OsmDbUpdatesCheck", {CLEAR_ON_MANAGER_START, BOOL}},  // mapd database update happens with device ON, reset on boot
    {"OSMDownloadBounds", {PERSISTENT, STRING}},
    {"OsmDownloadedDate", {PERSISTENT, STRING, "0.0"}},
    {"OSMDownloadLocations", {PERSISTENT, JSON}},
    {"OSMDownloadProgress", {CLEAR_ON_MANAGER_START, JSON}},
    {"MTSCEnabled", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"OsmLocal", {PERSISTENT, BOOL}},
    {"OsmLocationName", {PERSISTENT, STRING}},
    {"OsmLocationTitle", {PERSISTENT, STRING}},
    {"OsmLocationUrl", {PERSISTENT, STRING}},
    {"OsmStateName", {PERSISTENT, STRING, "All"}},
    {"OsmStateTitle", {PERSISTENT, STRING}},
    {"OsmWayTest", {PERSISTENT, STRING}},
    {"RoadName", {CLEAR_ON_ONROAD_TRANSITION, STRING, ""}},
    // VTSC map lookahead
    {"MTSCLookaheadEnabled", {PERSISTENT | BACKUP, BOOL, "0"}},
    // VTSC freeway fail-open guard (developer triage)
    {"VTSCFailOpen", {PERSISTENT | BACKUP, BOOL, "0"}},
    // VTSC verbose debug logging (rate-limited)
    {"VTSCVerboseDebug", {PERSISTENT | BACKUP, BOOL, "0"}},
    // VTSC onroad snapshot file writer (JSONL, small/rotating)
    {"VTSCWriteSnapshotFile", {PERSISTENT | BACKUP, BOOL, "0"}},
    // VTSC intervention recorder daemon (event bundles under /data/media/0/VTSCTuner/events)
    {"VTSCInterventionRecorderEnabled", {PERSISTENT | BACKUP, BOOL, "1"}},
    // VTSC occlusion arbitration tunables (psi gate + double-cap guard + fov_exit relax)
    {"VTSC.PsiThreshRad", {PERSISTENT | BACKUP, FLOAT, "0.020"}},
    {"VTSC.PsiHystRad", {PERSISTENT | BACKUP, FLOAT, "0.005"}},
    {"VTSC.DoubleCapEpsMps", {PERSISTENT | BACKUP, FLOAT, "0.30"}},
    {"VTSC.OcclConfFloor", {PERSISTENT | BACKUP, FLOAT, "0.05"}},
    {"VTSC.FovExitRelaxS", {PERSISTENT | BACKUP, FLOAT, "0.60"}},
    {"VTSC.OcclVminNudgeMps", {PERSISTENT | BACKUP, FLOAT, "0.50"}},
    // VTSC: occlusion bypass when following a lead
    {"VisionTurnSpeedControlOcclBypassWithLead", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"VisionTurnSpeedControlOcclBypassHeadwayS", {PERSISTENT | BACKUP, FLOAT, "3.0"}},

    // Speed Limit Control
    {"SpeedLimitControl", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"SpeedLimitControlPolicy", {PERSISTENT | BACKUP, STRING, "3"}},
    {"SpeedLimitEngageType", {PERSISTENT | BACKUP, STRING, "0"}},
    {"SpeedLimitOffsetType", {PERSISTENT | BACKUP, STRING, "0" }},
    {"SpeedLimitValueOffset", {PERSISTENT | BACKUP, STRING, "0"}},
    {"SpeedLimitWarningType", {PERSISTENT | BACKUP, STRING, "0"}},
    {"SpeedLimitWarningOffsetType", {PERSISTENT | BACKUP, STRING, "0"}},
    {"SpeedLimitWarningValueOffset", {PERSISTENT | BACKUP, STRING, "0"}},

    // Realtime Traffic Intelligence (RTI)
    {"RTIEnabled", {PERSISTENT | BACKUP, BOOL}},
    {"RTIDataSource", {PERSISTENT | BACKUP, STRING}},
    {"RTIThreatFilter", {PERSISTENT | BACKUP, STRING}},
    {"RTIAggressiveness", {PERSISTENT | BACKUP, INT}},
    {"RTIMinDistance", {PERSISTENT | BACKUP, INT}},
    {"RTIMaxDistance", {PERSISTENT | BACKUP, INT}},
    {"RTISpeedReduction", {PERSISTENT | BACKUP, INT}},
    {"RTISpeedReductionMode", {PERSISTENT | BACKUP, STRING}},
    {"RTIDetectionRadius", {PERSISTENT | BACKUP, INT}},
    {"RTIForwardSlowdownRange", {PERSISTENT | BACKUP, INT}},
    {"RTIResumeSpeedDistance", {PERSISTENT | BACKUP, INT}},
    {"RTIDuplicateCollapseRadius", {PERSISTENT | BACKUP, INT, "110"}},
    {"RTIPoliceCollapseRadius", {PERSISTENT | BACKUP, INT, "140"}},
    {"RTIHUDEnabled", {PERSISTENT | BACKUP, BOOL}},
    {"RTIAudioAlerts", {PERSISTENT | BACKUP, BOOL}},
    {"RTIManualApiEndpoint", {PERSISTENT | BACKUP, STRING}},
    {"RTIManualApiKey", {PERSISTENT | BACKUP | DONT_LOG, STRING}},
};
